### ISSUE TITLE
Fix copy_hex() to suit registry v2

### ISSUE THREAD

**Issue by jayjun** [HashNuke/heroku-buildpack-elixir#105]
[`copy_hex()`](https://github.com/HashNuke/heroku-buildpack-elixir/blob/master/lib/app_funcs.sh#L32) copies `registry.ets` to the build directory, but this file is no longer fetched after Hex 0.14.0 introduced registry v2.

On the other hand, I'm not sure if `cache.ets` is the right substitute as well.

As a sidenote, `cache.ets` isn't generated by running `mix deps.get`. Seems silly to run `mix hex.info` just so you can copy this file over.

**Comment by ericmj** [comment]
We should copy the entire `~/.hex` directory.

> As a sidenote, cache.ets isn't generated by running mix deps.get

That will be fixed in the next version of Hex.
