### ISSUE TITLE
Phoenix heroku bash: mix: command not found

### ISSUE THREAD

**Issue by Wulpo** [HashNuke/heroku-buildpack-elixir#107]
I try to create elixir/phoenix project on heroku with this manual: http://www.phoenixframework.org/docs/heroku

    wulp@wulp-vb:~/Documents/chatmeapp$ heroku create chatmeapp --buildpack "https://github.com/HashNuke/heroku-buildpack-elixir.git"
    Creating ⬢ chatmeapp... done
    Setting buildpack to https://github.com/HashNuke/heroku-buildpack-elixir.git... done
    https://chatmeapp.herokuapp.com/ | https://git.heroku.com/chatmeapp.git
    
    wulp@wulp-vb:~/Documents/chatmeapp$ heroku git:remote -a chatmeapp
    set git remote heroku to https://git.heroku.com/chatmeapp.git
    
    wulp@wulp-vb:~/Documents/chatmeapp$ heroku buildpacks:add https://github.com/gjaldon/heroku-buildpack-phoenix-static.git
    Buildpack added. Next release on chatmeapp will use:
      1. https://github.com/HashNuke/heroku-buildpack-elixir.git
      2. https://github.com/gjaldon/heroku-buildpack-phoenix-static.git
    Run git push heroku master to create a new release using these buildpacks.
    
    wulp@wulp-vb:~/Documents/chatmeapp$ heroku addons:create heroku-postgresql:hobby-dev
    Creating heroku-postgresql:hobby-dev on ⬢ chatmeapp... free
    Database has been created and is available
     ! This database is empty. If upgrading, you can transfer
     ! data from another database with pg:copy
    Created postgresql-tetrahedral-49526 as DATABASE_URL
    Use heroku addons:docs heroku-postgresql to view documentation
    
    wulp@wulp-vb:~/Documents/chatmeapp$ heroku config:set POOL_SIZE=18
    Setting POOL_SIZE and restarting ⬢ chatmeapp... done, v4
    POOL_SIZE: 18
    
    wulp@wulp-vb:~/Documents/chatmeapp$ heroku run "POOL_SIZE=2 mix chatmeapp.task"
    Running POOL_SIZE=2 mix chatmeapp.task on ⬢ chatmeapp... up, run.1524 (Free)
    bash: mix: command not found

But I have error: bash: mix: command not found

**Comment by HashNuke** [comment]
@Wulpo Going by the commands, looks like only the phoenix buildpack was added. The Elixir buildpack needs to be added too.

**Comment by ericmj** [comment]
You need to push the code before you can run tasks.

**Comment by HashNuke** [comment]
@ericmj Oh that ~! I missed it 🥇
