### ISSUE TITLE
Elixir 1.6 support

### ISSUE THREAD

**Issue by scorsi** [HashNuke/heroku-buildpack-elixir#129]
Hi,

Is Elixir 1.6.0 supported ?
If so, how can I use it properly ? I see in the `elixir_buildpack.config` file that the elixir version is in, but how can apply the modification to the heroku buildpack ?

Thanks,

**Comment by ericmj** [comment]
Yes. You create a `elixir_buildpack.config` file in your own project with `elixir_version=1.6.6` set to use it.

**Comment by scorsi** [comment]
Oh ok, thank you.
