### ISSUE TITLE
Over-aggressive cache nuking?

### ISSUE THREAD

**Issue by pwightman** [HashNuke/heroku-buildpack-elixir#138]
Hi,

I was [running into a strange issue](https://github.com/emk/heroku-buildpack-rust/issues/37) when trying to use the [Rust buildpack](https://github.com/emk/heroku-buildpack-rust) to make `cargo` available during my Phoenix app's compilation so that [Meeseeks](https://github.com/mischov/meeseeks) can compile its nif correctly.

Short version of the issue: By the time the Elixir app was compiling, `cargo` was no longer available in the cache directory, despite the Rust buildpack placing it there.

The maintainer of meeseeks was able to [track it down](https://github.com/mischov/meeseeks/issues/49#issuecomment-446366989) to this buildpack nuking the entire cache directory when the stack changes.

https://github.com/HashNuke/heroku-buildpack-elixir/blob/651bb3d24e9538e158858591499bbcb166ebbb94/lib/misc_funcs.sh#L78-L81

I was able to confirm that, after removing the rust dependency and successfully deploying once, adding back the rust dependency causes deployment to work just fine, it was only failing on the initial deploy due to this stack check.

Would it be appropriate to modify this code to only `rm -rf` the directories it uses, instead of everything in the cache directory? Is that an easily enumerated list of directories?

**Comment by mischov** [comment]
To further expand, `${cache_path}/stack` doesn't exist for the first build, so it nukes the cache, destroying the things put there by the Rust buildpack which are then required during Elixir complication, and the whole build fails and `${cache_path}/stack` can never be created.

**Comment by HashNuke** [comment]
@mischov @pwightman 
Hello folks,
Thanks to @anulman and @axelson this issue should have been fixed ~!
Can you confirm and if yes also close this issue?

P.S: https://github.com/HashNuke/heroku-buildpack-elixir/pull/146
