### ISSUE TITLE
Failed to install Erlang 21.2

### ISSUE THREAD

**Issue by thezjy** [HashNuke/heroku-buildpack-elixir#141]
After I changed Erlang from 20.1 to 21.2, the script failed like this:

> -----> Fetching Erlang 21.2 from https://s3.amazonaws.com/heroku-buildpack-elixir/erlang/cedar-14/OTP-21.2.tar.gz
-----> Installing Erlang 21.2 (changed)
remote:
remote: gzip: stdin: not in gzip format
remote: tar: Child returned status 1
remote: tar: Error is not recoverable: exiting now
remote: /tmp/buildpackcFN3P/lib/erlang_funcs.sh: line 37: /tmp/cache/erlang/Install: No such file or directory

**Comment by duff** [comment]
@thezjy I saw the same thing here. I'm unsure if the solution is a simple PR updating [this file](https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/blob/master/otp-versions). The [README](https://github.com/HashNuke/heroku-buildpack-elixir#version-support) seems to indicate that.

**Comment by anthonator** [comment]
Running into the same issue

**Comment by duff** [comment]
It looks like [This PR](https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/pull/52) addresses the issue.

**Comment by HashNuke** [comment]
Closing issue since this has been resolved.
