### ISSUE TITLE
create new release v4

### ISSUE THREAD

**Issue by petermm** [HashNuke/heroku-buildpack-elixir#145]
which will then be picked up heroku https://elements.heroku.com/buildpacks/hashnuke/heroku-buildpack-elixir

and contain all the fixes since  v3 · Oct 23, 2015 · (73 commits)

@HashNuke ?

**Comment by eprothro** [comment]
Are there any plans to publish a release of this buildpack to Heroku to support using the latest buildpack features without having to use a github reference (e.g. seems to be a Heroku buildpacks best-practice)?

**Comment by eprothro** [comment]
I should have added, given https://github.com/HashNuke/heroku-buildpack-elixir/pull/214 fixed by @ericmj, moving forward the latest buildpack released to Heroku will not work for anyone, so it would seem to me the urgency of this issue is higher now.

**Comment by HashNuke** [comment]
@eprothro Thank you for commenting on this ticket. Caught my attention. I tagged v4 and published a new release on Heroku.

**Comment by eprothro** [comment]
@HashNuke thank you! 🙌🏼
