### ISSUE TITLE
Erlang 21.3.5 not found

### ISSUE THREAD

**Issue by fbjork** [HashNuke/heroku-buildpack-elixir#147]
Seeing this error when I try to upgrade Erlang to 21.3.5:

```
-----> Fetching Erlang 21.3.5 from https://s3.amazonaws.com/heroku-buildpack-elixir/erlang/cedar-14/OTP-21.3.5.tar.gz
-----> Installing Erlang 21.3.5 (changed)
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by HashNuke** [comment]
* We have the following supported versions - https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/blob/master/otp-versions

* I've added 21.3.7. I skipped 21.3.4, 21.3.5 and 21.3.6 - https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/pull/70

* Once the build is complete the new version will be available. This usually takes about 30min.

Thank you for reporting this. Closing issue.
