### ISSUE TITLE
Update elixir version

### ISSUE THREAD

**Issue by anandpotukchi** [HashNuke/heroku-buildpack-elixir#154]
update elixir to 1.9.0

**Comment by franzejr** [comment]
@anandpotukchi this worked for you ? When I try to use this in Heroku it doesn't work

**Comment by axelson** [comment]
Can't you just set `elixir_version=1.9.0`  (or 1.9.1) in your elixir_buildpack.config? Is that not working for you?

**Comment by silentsilas** [comment]
I've set my elixir_buildpack.config to 

```
elixir_version=1.12.1
erlang_version=24.0.2
```

And it says _Sorry, Erlang 24.0.2 isn't supported yet._

This is unfortunate since Erlang 24 provides a huge performance boost.

**Comment by jesseshieh** [comment]
Erlang 24 is supported, but it looks like 24.0.2 wasn't in the list. I just added it. It may take a few minutes to build, but afterwards, give it another try.
https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/blob/master/otp-versions

**Comment by silentsilas** [comment]
Ah, gotcha! Erlang 24.0.2 is working now.
