### ISSUE TITLE
Phoenix 1.14.10 Error: Web process failed to bind to $PORT within 60 seconds of launch

### ISSUE THREAD

**Issue by toranb** [HashNuke/heroku-buildpack-elixir#161]
I created a new Phoenix 1.4.10 app and get the following after I deploy to `heroku-18`

```Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch```

I'm using these settings in my prod.exs

```
config :demo, DemoWeb.Endpoint,
  load_from_system_env: true,
  http: [:inet6, port: String.to_integer(System.get_env("PORT") || "4000")],
  url: [scheme: "https", host: "elixirprimes.herokuapp.com", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]]
```

I'm using this elixir_buildpack.config

```
elixir_version=1.8.1
erlang_version=21.2.5
```

The application is 100% public/ just a demo app so I've put it on github if anyone finds the example helpful

https://github.com/toranb/elixir-primes-demo/commit/69e8a83c495189cdafc5c1c2901e39611ef92645

**Comment by jesseshieh** [comment]
Try adding server: true to the endpoint config

**Comment by toranb** [comment]
@jesseshieh thank you !!!! [This](https://github.com/toranb/elixir-primes-demo/commit/caaf0a6820577ac084e1071e50882c039cd9f453) worked perfectly :)

```
config :demo, DemoWeb.Endpoint,
  server: true,
  load_from_system_env: true,
  http: [:inet6, port: String.to_integer(System.get_env("PORT") || "4000")],
  url: [scheme: "https", host: "elixirprimes.herokuapp.com", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]]
```

**Comment by toranb** [comment]
@jesseshieh to help people who might bump into this like I did ... where is this documented today? And if it isn't how should/could I contribute to highlight this for new Phoenix deployments?

**Comment by jesseshieh** [comment]
It's mentioned here
https://github.com/toranb/elixir-primes-demo/blob/master/config/prod.secret.exs

But if you're not using releases/distillery, it really shouldn't be necessary so that's kinda strange. What buildpacks are you using?

**Comment by jesseshieh** [comment]
Oh I see. I haven't verified this, but I think because you're using heroku docker deploys, the default command is "iex" instead of "mix phx.server". Anything except phx.server needs the server: true option.

**Comment by toranb** [comment]
![Screen Shot 2019-10-25 at 10 07 09 AM](https://user-images.githubusercontent.com/147411/67582355-3eb30300-f70f-11e9-8bd3-c97d558dc014.png)

I tried to use Docker but ultimately failed as it's not supported (that I'm aware of)

**Comment by toranb** [comment]
Regardless of the outcome here I've decide to update the Phoenix docs so other people deploying to Heroku like I was don't get stuck/ give up :)

https://github.com/phoenixframework/phoenix/pull/3597
