### ISSUE TITLE
Comparison to heroku version of buildpack

### ISSUE THREAD

**Issue by axelson** [HashNuke/heroku-buildpack-elixir#173]
Is there any sort of comparison between this version of the buildpack and "heroku's version": https://github.com/heroku/heroku-buildpack-elixir

It is a fork of this repository and doesn't have any of it's own commits in it. Is there any reason to use it over this? I'm guessing the answer is no.

**Comment by jesseshieh** [comment]
Afaik, the answer is indeed no, but I'm not that familiar with the history.

**Comment by HashNuke** [comment]
I just checked the commit history.
* They seem to have included some github workflows for a changelog.
So yes, this repo is still the the one to use.
