### ISSUE TITLE
Will use cached Elixir version even if Erlang version changes

### ISSUE THREAD

**Issue by jbrowning** [HashNuke/heroku-buildpack-elixir#178]
This buildpack does not ensure that the cached Elixir version is compatible when the Erlang major version is updated. This results in an error similar to the following:

```
-----> Cleaning all cache to force rebuilds
-----> Using cached Erlang 22.2.3
-----> Installing Erlang 22.2.3

-----> Using cached Elixir v1.11.2
-----> Installing Elixir v1.11.2
-----> Installing Hex
remote: init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_eremote: {init,do_boot,3,[]}]})
       {"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_remote: ,{init,do_boot,3,[]}]}}
remote:
remote: Crash dump is being written to: erl_crash.dump...done
-----> Installing rebar
remote: init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_eremote: {init,do_boot,3,[]}]})
       {"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_remote: ,{init,do_boot,3,[]}]}}
remote:
remote: Crash dump is being written to: erl_crash.dump...done
-----> Fetching app dependencies with mix
remote: init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_eremote: {init,do_boot,3,[]}]})
       {"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_remote: ,{init,do_boot,3,[]}]}}
remote:
remote: Crash dump is being written to: erl_crash.dump...done
```

To recreate:

* Deploy with any version of Elixir and Erlang 23.x
* Change the Erlang version to 22.x and redeploy

**Comment by jesseshieh** [comment]
Thanks for the bug report @jbrowning. I guess we could try and implement something to check the compatibility matrix described here
https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

Perhaps in this function which checks the erlang version.
https://github.com/HashNuke/heroku-buildpack-elixir/blob/master/lib/canonical_version.sh#L20

Any help implementing this would be greatly appreciated!

**Comment by hez** [comment]
We had this happen and had to turn off caching completely.  We could turn it on then turn it off on lang update but that seems like a lot of work.

**Comment by hez** [comment]
@jesseshieh I would suggest tagging the cache with the otp + elixir ver and invalidating it if it changes at all. That would be easiest and cover all bases.

**Comment by jesseshieh** [comment]
Thanks @hez. I like that suggestion.

Right now, according to [this](https://github.com/HashNuke/heroku-buildpack-elixir/blob/1251439227711cf28bbfbafc101f9c9ff7f9345a/lib/elixir_funcs.sh#L45) we basically check for `${cache_path}/elixir-${elixir_version}.zip`

We could change this to `${cache_path}/elixir-${elixir_version}-otp-${erlang_version}.zip`

The file we download usually looks something like this anyway:
```
-----> Fetching Elixir v1.10.3 for OTP 22 from https://repo.hex.pm/builds/elixir/v1.10.3-otp-22.zip
```

The [code that fetches it](https://github.com/HashNuke/heroku-buildpack-elixir/blob/1251439227711cf28bbfbafc101f9c9ff7f9345a/lib/elixir_funcs.sh#L8) even uses the `otp_version` and then throws it away when writing the `elixir_download_file`. I wonder if perhaps the otp_version is all we need rather than the entire `erlang_version`.

**Comment by jbrowning** [comment]
@jesseshieh Yeah `elixir_version` + `otp_version` like the original filename is all you need to retain in order to fix this. Minor Erlang version changes will still download the same OTP version.

**Comment by jesseshieh** [comment]
I just submitted a pull request with a potential fix. I tested it briefly and it seems to work. If you guys want to try it out, change your buildpack to `https://github.com/jesseshieh/heroku-buildpack-elixir#js/elixir-otp-version-cache` and see if everything works okay.
