### ISSUE TITLE
Crypto.app not found

### ISSUE THREAD

**Issue by bbassett** [HashNuke/heroku-buildpack-elixir#181]
I'm trying to upgrade an old elixir app that is still running on cedar-14 to run on heroku-20. I have gotten as far as i can, but there seems to be something wrong and the only thing I can think of is the buildpack. 

I'll include the build output, but what i'm assuming is that the erlang version included wasn't compiled with ssl enabled? seems odd to me, but i'm wondering if someone with more understanding can point me in the right direction. 

```       * MIX_ENV=prod

-----> Checking Erlang and Elixir versions

       Will use the following versions:

       * Stack heroku-20

       * Erlang 17.5.6.6

       * Elixir v1.0.4 

-----> Stack changed, will rebuild

-----> Cleaning all cache to force rebuilds

-----> Fetching Erlang 17.5.6.6 from https://github.com/elixir-buildpack/heroku-otp/releases/download/17.5.6.6/heroku-20.tar.gz

-----> Installing Erlang 17.5.6.6 (changed)

-----> Using cached Elixir v1.0.4

-----> Installing Elixir v1.0.4 

-----> Installing Hex

{"init terminating in do_boot",{{badmatch,{error,{crypto,{"no such file or directory","crypto.app"}}}},[{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,78}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}```

**Comment by jesseshieh** [comment]
I don't think this buildpack works with heroku-20 right now. See the README.
