### ISSUE TITLE
"unary operator expected" error at Bluemix

### ISSUE THREAD

**Issue by optikfluffel** [HashNuke/heroku-buildpack-elixir#23]
Hi,

I just tried to deploy your buildpack to [Bluemix](https://bluemix.net) and got this error messages:

```
Cloning into '/tmp/buildpacks/heroku-buildpack-elixir'...
-----> Checking Erlang and Elixir versions
       Will use the following versions:
       * Stack 
       * Erlang 17.4
       * Elixir 1.0.2 
       Will export the following config vars:
       * Config vars DATABASE_URL
       * MIX_ENV=prod
-----> Cleaning all cache to force rebuilds
/tmp/buildpacks/heroku-buildpack-elixir/lib/erlang_funcs.sh: line 7: [: =: unary operator expected
-----> Fetching Erlang 17.4
-----> Installing Erlang 17.4
-----> Fetching Elixir v1.0.2
-----> Installing Elixir v1.0.2
/tmp/buildpacks/heroku-buildpack-elixir/lib/elixir_funcs.sh: line 25: [: =: unary operator expected
/tmp/buildpacks/heroku-buildpack-elixir/lib/elixir_funcs.sh: line 28: jar: command not found
chmod: cannot access `/tmp/staged/app/.platform_tools/elixir/bin/*': No such file or directory
-----> Installing Hex
/tmp/buildpacks/heroku-buildpack-elixir/lib/elixir_funcs.sh: line 94: mix: command not found
-----> Installing rebar
/tmp/buildpacks/heroku-buildpack-elixir/lib/elixir_funcs.sh: line 109: mix: command not found
-----> Fetching app dependencies with mix
```

where could this `unary operator expected` come from?

Thanks in advance

**Comment by ericmj** [comment]
It seems like Bluemix doesn't set the `STACK` environment variable, see https://devcenter.heroku.com/articles/buildpack-api#stacks. The buildpack is built for Heroku and other providers using buildpacks should probably match the environment Heroku buildpacks run in.

I suggest you raise this issue with Bluemix, please let us know their response, keeping this issue open.

**Comment by HashNuke** [comment]
@ericmj You are right about the STACK var. I read this issue in bed and forgot to reply. Ideally some Heroku buildpacks work on alternative platforms (like CloudFoundry in this case). But I wrote this buildback intending to work on Heroku only (only after noticing the tiny diff that each env seemed to have), but did have supporting other platforms in mind IF possible in the future.

Right now I think it might be tough for you to build/maintain multiple versions of Erlang. It might depend which distro/version of Linux the container runs (assuming knowing the ubuntu version is how you build Erlang pkgs stored on s3). If cloudfoundry, openstack, heroku etc all require diff Erlang pkgs for a particular version, I'll leave it upto you to decide if you want to support them.

P.S: I'll get back with some OS-version numbers that these platforms use in some time.

**Comment by ericmj** [comment]
@HashNuke You are making a good point, unless the alternative platforms use the exact ubuntu versions (and updates) as Heroku does the Erlang builds are not going to work.

I don't have time to maintain Erlang builds for all possible linux containers on every platform. If someone wants to maintain builds for their specific platform we can of course try to support that in the buildpacl

**Comment by HashNuke** [comment]
> If someone wants to maintain builds for their specific platform we can of course try to support that in the buildpack

@ericmj :+1:

**Comment by optikfluffel** [comment]
Ok, the `cf stacks` command tells me there is only one available stack on Bluemix right now, it's called `lucid64` and is running `Ubuntu 10.04 on x86-64`. Isn't that the same as `cedar` on Heroku?

**Comment by HashNuke** [comment]
@optikfluffel As far as I can remember yes. In that case, you can set the STACK var manually to "cedar" and the buildpack might work.

**Comment by optikfluffel** [comment]
@HashNuke tried it out, now I'm getting `ERR /tmp/buildpacks/heroku-buildpack-elixir/lib/elixir_funcs.sh: line 28: jar: command not found`. I already saw #18 but there the problem was the newer cedar-14 stack.

**Comment by HashNuke** [comment]
@optikfluffel jar command was the only way to unzip files on the older cedar stack. cedar14 doesn't have jar but has unzip. So we check for stack name and use unzip/jar depending on the stack https://github.com/HashNuke/heroku-buildpack-elixir/blob/master/lib/elixir_funcs.sh#L25-L29

My suggestion would be to actually check which command exists using a cross-shell way like "command -v foo" instead of the stack var. Then use that command. Try making the change in a fork and deploy using that fork (PR welcome if it works ~!).

If you've got Erlang installed without errors then there's a high probability that you will get a proper deploy with this fix.
