### ISSUE TITLE
Should we set the "+K true" and "+A 100" Erlang flags?

### ISSUE THREAD

**Issue by josevalim** [HashNuke/heroku-buildpack-elixir#25]

**Comment by ericmj** [comment]
What does it do and what are the defaults?

**Comment by josevalim** [comment]
+K enables kernel polling. Which may slightly degrade performance but it works great for chunking, long lived connections (be it for slow clients or waiting on the server and so on) and so on.

+A 100 is the size of the async pool. Interacting with the file system usually goes through the async pool. Increasing the pool increasing boot time but it will likely increase performance for the plug static layer. 

We could benchmark to be double sure.

**Comment by ericmj** [comment]
Okay, thanks for the information. Lets start with allowing you to set erlang flags through elixir_buildpack.config. If benchmarks show that changing the flags will improve performance we can change the defaults. Sounds good?

Would also like @HashNuke's opinions before signing off.

**Comment by HashNuke** [comment]
@ericmj +1 for making it configurable.
@josevalim are there any more interesting flags we could use?

What code should we be using for benchmarking?

**Comment by ericmj** [comment]
I've been using this on hex_web for a while with no issues https://github.com/hexpm/hex_web/blob/master/Procfile.

I think we should set the default Procfile to set the flags and document that we recommend setting them. The phoenix buildpack should probably do the same. /cc @gjaldon

**Comment by gjaldon** [comment]
Copy that @ericmj. I'll apply the configurable erlang flags too and apply the suggested flags as defaults.

**Comment by AndrewDryga** [comment]
In OTP 21 those flags are deprecated (kernel polling is already on by default) and `+A` is replaced with dirty IO schedulers. I'm not sure should we increase default value of 10 or not though.

**Comment by ericmj** [comment]
We should close this issue and let users decide what they prefer, especially since the flag does different things for different OTP versions.
