### ISSUE TITLE
Try detect if application is not running in permanent mode

### ISSUE THREAD

**Issue by ericmj** [HashNuke/heroku-buildpack-elixir#29]
Elixir 1.0.4 will add CLI and mix.exs options to run application in permanent mode. Permanent mode ensures that the process will crash if the application crashes so Heroku will restart the process.

It is important to run in permanent mode on Heroku so we should try to detect if the app is not running with it and print a simple warning.

/cc @josevalim

**Comment by edgurgel** [comment]
:+1:

**Comment by cmaggard** [comment]
:+1:

**Comment by ericmj** [comment]
The options we should check for are `:build_embedded`, `:consolidate_protocols` and `:start_permanent`.

**Comment by josevalim** [comment]
Btw, :build_embedded already sets :consolidate_protocols.
