### ISSUE TITLE
Support post compile hook

### ISSUE THREAD

**Issue by chrismccord** [HashNuke/heroku-buildpack-elixir#31]
For Phoenix, we would like to have a complete buildpack solution when we ship 1.0, which means we need to be able to build brunch assets after compile. I'm not sure where to start here, but @ericmj has some idea where we need to begin.

**Comment by HashNuke** [comment]
@chrismccord won't that mean we would need node.js installed too? (https://github.com/ddollar/heroku-buildpack-multi).

\\cc: @ericmj

**Comment by rwdaigle** [comment]
Just an FYI that Heroku Buildpacks have changed a bit. You no longer need the multi-buildpack to specify a build pipeline. Instead, specify each buildpack individually with the following CLI:

```session
$ heroku buildpacks:set https://github.com/HashNuke/heroku-buildpack-elixir.git
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs
```

Regarding brunch asset compilation, here's how they do it in the [official Ruby/Rails buildpack](https://github.com/heroku/heroku-buildpack-ruby/blob/a83153a18f8c17416dd84bf597232c27ffbd2300/lib/language_pack/ruby.rb#L96).

**Comment by ericmj** [comment]
Should we automatically run a `post_compile` / `post_compile.sh` file in your root directory or should we take the file from a `post_compile` option in `elixir_buildpack.config`?

/cc @josevalim

**Comment by josevalim** [comment]
I thought the plan was to **not** support hooks. What changed? :)

**Comment by HashNuke** [comment]
At work, I was working with a non-Heroku deployed app where the `compilers` option in `mix.exs` was used to add a `:frontend` compiler so that everytime the app is started or compiled, the frontend too gets compiled.

Curious how a post compile hook will help on Heroku since we depend on mutl-buildpack for asset compilation.

**Comment by ericmj** [comment]
>At work, I was working with a non-Heroku deployed app where the compilers option in mix.exs was used to add a :frontend compiler so that everytime the app is started or compiled, the frontend too gets compiled.

The problem is that you might not want to compile assets on every compilation or app start so a Heroku specific compilation step is very useful.

> Curious how a post compile hook will help on Heroku since we depend on mutl-buildpack for asset compilation.

Not sure what you are asking here, as long as the node buildpack runs before the elixir buildpack it will work.

**Comment by HashNuke** [comment]
@ericmj I meant to ask what the use case was for the post-compile hook. I remember there was this discussion earlier in another issue and that that issue was closed.

Sorry read your comment in bed and forgot to reply the other day.

**Comment by ericmj** [comment]
https://github.com/phoenixframework/phoenix/issues/835

**Comment by HashNuke** [comment]
@ericmj :+1: thanks for linking. Got it now ~!

**Comment by HashNuke** [comment]
Yaaay ~!
