### ISSUE TITLE
Don't require `always_rebuild=true` to pull in app changes

### ISSUE THREAD

**Issue by rwdaigle** [HashNuke/heroku-buildpack-elixir#34]
I'm seeing the following behavior in my Phoenix app on Heroku using this buildpack. I wonder if I'm doing something wrong...

My app deploys to Heroku fine the first time and runs without issue. However, subsequent deploys don't pick up any changes made since the previous deploy. If I edit a model, that new model source exists on Heroku after the build (when I browse the dyno filesystem via `heroku run bash`), but when running the app it's still using the previous build's compiled code (as evidence by the new functionality not being executed nor any stack trace line numbers matching the new source).

If I add `always_rebuild=true` to my `elixir_buildpack.config`, the app is recompiled and new changes are properly executed. However, as you know, that incurs a pretty stiff penalty as each deploy now requires the whole world to be recompiled.

Is this expected behavior?

My `Procfile` is (this behavior exists for both versions of the `web` process type):

```
# web: mix phoenix.server
web: yes | mix compile.protocols && elixir -pa _build/prod/consolidated -S mix phoenix.server
```

Here's my `elixir_buildpack.config`

```
erlang_version=17.5
elixir_version=1.0.4
always_rebuild=true
```

**Comment by ericmj** [comment]
This is not expected behaviour, can you share a project that reproduces?

Alos, use :build_embedded and set your Procfile to: `web: mix phoenix.server`. See http://blog.plataformatec.com.br/2015/04/build-embedded-and-start-permanent-in-elixir-1-0-4/.

**Comment by rwdaigle** [comment]
@ericmj here is [the project](https://github.com/rwdaigle/markbox-files)

`:build_embedded` is [already set](https://github.com/rwdaigle/markbox-files/blob/master/mix.exs#L10)

The `Procfile` change didn't seem to change anything when I tried it before, let me know if you want me to retry.

**Comment by ericmj** [comment]
I can reproduce the behaviour and am debugging to find out what is
happening. It does not happen on a fresh project or on none of the apps I
run on heroku so it is probably some dependencies or configuration that is
causing the bug.

**Comment by rwdaigle** [comment]
I hate to think of people spending their time debugging my issue. Sorry!

To give a clue, I think the only thing I've done from the base Phoenix template is manually disable the Ecto dependency. Perhaps in my spelunking there I turned something off that shouldn't be?

I can always regenerate the app template and move my logic over if you think that would be more expedient?

**Comment by ericmj** [comment]
I found the issue, it was related to copying cached builds did not preserve mtimes so Elixir did not correctly detect the changes. I have no idea why it only happened in your project.

I have it fixed in a branch with some other changes. You can use it by setting your buildpack to `https://github.com/HashNuke/heroku-buildpack-elixir.git#emj`.

**Comment by rwdaigle** [comment]
Thank you so much, @ericmj!
