### ISSUE TITLE
Do we have a standard sample app that contributors can quickly use to test deploys?

### ISSUE THREAD

**Issue by HashNuke** [HashNuke/heroku-buildpack-elixir#36]
This could be using the new Heroku Review apps feature - https://blog.heroku.com/archives/2015/5/19/heroku_review_apps_beta

**Comment by rwdaigle** [comment]
I believe Review apps are more for tracking development branches so may not be appropriate for quick sample apps? However, a sample app with a [Heroku Button](https://devcenter.heroku.com/articles/heroku-button) seems like the ideal approach?

Does there already exist a standard sample app we can tweak to include this?

**Comment by HashNuke** [comment]
No standard app yet. I was thinking we could just use the hex web app as a standard one to test with. It's always updated and seems like a good test subject.

**Comment by ericmj** [comment]
I can create an app.json for hex_web if needed.

**Comment by HashNuke** [comment]
+1 Eric
That should help a lot with testing changes quickly

**Comment by HashNuke** [comment]
@ericmj Oh sorry ~! just checked. The buildpack URL is hardcoded in the app.json. IMHO for pull requests they'll have to use their own fork's url. https://devcenter.heroku.com/articles/app-json-schema

**Comment by HashNuke** [comment]
@ericmj I have a vague idea.
We can include a sample plug app within the buildpack, host it on Heroku and enable review apps. So when anyone sends a PR, an app gets deployed. This is under the assumption that the heroku app is owned by the one who sends a PR.

**OR** we can just keep it simple and have a repo for a sample app. Ask people to copy-paste a command from the app repo's readme to host it using their fork of the buidpack

**Comment by ericmj** [comment]
How do we change the buildpack url for PRs?

**Comment by ericmj** [comment]
Doing this automatically will not give us much benefit since I don't think there is a way to get the buildpack output for review apps.

**Comment by HashNuke** [comment]
@ericmj Oh. Closing this issue then. Unless we find something nicer.
