### ISSUE TITLE
Hex 0.9.0 issue when updating Elixir to 1.1.0

### ISSUE THREAD

**Issue by chrismcg** [HashNuke/heroku-buildpack-elixir#50]
Just tried updating a heroku app to 1.1.0 by updating the `elixir_version` in my elixir_buildpack.config.

When I push to heroku I get:

```
remote: -----> Using cached Elixir v1.1.0
remote: -----> Installing Elixir v1.1.0
remote: -----> Installing Hex
remote: * creating /app/.mix/archives/hex-0.9.0.ez
remote: -----> Installing rebar
remote: * creating /app/.mix/rebar
remote: -----> Fetching app dependencies with mix
remote: Running dependency resolution
remote: All dependencies up to date
remote: cp: cannot stat ‘/app/.mix/archives/hex.ez’: No such file or directory
```

The compilation proceeds and the slug is built and deployed but when I hit the application I get an error and the following in the heroku logs:

```
2015-09-26T15:00:48.868977+00:00 heroku[web.1]: Starting process with command `mix phoenix.server`
2015-09-26T15:00:51.827994+00:00 app[web.1]: Shall I install Hex? [Yn] ** (Mix) Could not find an SCM for dependency :phoenix from Phlink.Mixfile
2015-09-26T15:00:51.811929+00:00 app[web.1]: Could not find Hex, which is needed to build dependency :phoenix
2015-09-26T15:00:52.694003+00:00 heroku[web.1]: State changed from starting to crashed
2015-09-26T15:00:52.683127+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by HashNuke** [comment]
@chrismcg This is happening because the hex source path is different (has version number appended to it). Looking into it right away.

**Comment by HashNuke** [comment]
@chrismcg no worries. Found your buildpack config

**Comment by ericmj** [comment]
Is this fixed now?

**Comment by chrismcg** [comment]
@ericmj alas no, I've just finished trying out the PR and there's something up with how `basename` is being called

**Comment by ericmj** [comment]
@chrismcg `master` doesn't work either?

**Comment by chrismcg** [comment]
@ericmj master works for 1.1.0 but fails on 1.0.5 :(

**Comment by chrismcg** [comment]
@ericmj @HashNuke https://github.com/HashNuke/heroku-buildpack-elixir/pull/52 deploys both 1.0.5 and 1.1.0 ok for my test app

**Comment by avitex** [comment]
Any idea when #53 will be pulled in? :smile:

**Comment by HashNuke** [comment]
@ericmj Chris's PR fixed the issue. Merged it in.
