### ISSUE TITLE
Hex installation is broken

### ISSUE THREAD

**Issue by ericmj** [HashNuke/heroku-buildpack-elixir#54]
Build output:

```
Copying hex from
remote: cp: missing destination file operand after ‘/tmp/build_7239412cab625558e211972bd15b7208/.mix/archives’
remote: Try 'cp --help' for more information.
```

The app crashes at startup with:

```
Shall I install Hex? [Yn] ** (Mix) Could not find an SCM for dependency :plug from HexWeb.Mixfile
```

/cc @HashNuke @chrismcg

**Comment by ericmj** [comment]
It's possibly only happening with a custom hex_source.

**Comment by ericmj** [comment]
Confirmed that it only happens with `hex_source` set in `elixir_buildpack.config`. We can drop support for `hex_source` now that Elixir doesn't go through Hex API servers anymore when installing Hex.

**Comment by HashNuke** [comment]
Closing. Support for custom `hex_source` has been removed.
