### ISSUE TITLE
Override MIX_ENV

### ISSUE THREAD

**Issue by fbjork** [HashNuke/heroku-buildpack-elixir#55]
I can't get MIX_ENV to be overridden when deploying my Elixir app to Deis (http://deis.io). All other ENV variables can be exported, but MIX_ENV=prod is always set by default.

What am I doing wrong?

**Comment by ericmj** [comment]
Can you show how you set it?

**Comment by fbjork** [comment]
`deis config:set MIX_ENV=staging`

**Comment by fbjork** [comment]
It works on Heroku, so it must be something specific to Deis. 

Either here:
https://github.com/HashNuke/heroku-buildpack-elixir/blob/603793a2c4ec35d1c70eec166bebc72e67d796d2/lib/misc_funcs.sh#L59

or here:
https://github.com/HashNuke/heroku-buildpack-elixir/blob/603793a2c4ec35d1c70eec166bebc72e67d796d2/lib/app_funcs.sh#L87

**Comment by ericmj** [comment]
I'm afraid you are on your own for this since the buildpack was built for and tested with Heroku. I know others have reported issues when using it with Deis. If you find a fix please send a PR or if someone has ideas for fixes please drop comments here.

**Comment by HashNuke** [comment]
I found info that can be used for the PR if @fbjork or anyone is interested. It's deis being different here. The comments I found on a github issue on the deis project have details.

* problem - https://github.com/deis/deis/issues/1568#issuecomment-57026718
* solution - https://github.com/deis/deis/issues/1568#issuecomment-57242372
