### ISSUE TITLE
provide a package for elixir 1.2

### ISSUE THREAD

**Issue by docteurklein** [HashNuke/heroku-buildpack-elixir#61]
Is there a plan to support this new version?

**Comment by ericmj** [comment]
It is already supported, example usage is in the readme.

**Comment by docteurklein** [comment]
oh I'm sorry, I checkd 4 days ago and didn't see https://github.com/HashNuke/heroku-buildpack-elixir/commit/ac9fb37744d47f46d6732b896f31ef79ab9bdb8f

Sorry for the noise.

**Comment by ericmj** [comment]
Elixir is built and ready to use in the buildpack immediately after a new elixir version is released. Updating the buildpack defaults and documentation is usually more delayed.
