### ISSUE TITLE
Support option to skip reusing cached _build folder upon deployment

### ISSUE THREAD

**Issue by seantanly** [HashNuke/heroku-buildpack-elixir#63]
I ran into this issue after upgrading the dependencies in my app, which upgraded fine on my local machine, but not on the Dokku server.

```
remote: Dependencies have diverged:
remote: * postgrex (Hex package)
remote:   the dependency postgrex
remote:
remote:   > In mix.exs:
remote:     {:postgrex, ">= 0.0.0", [hex: :postgrex, manager: :mix]}
remote:
remote:   does not match the requirement specified
remote:
remote:   > In deps/ecto/mix.exs:
remote:     {:postgrex, "~> 0.11.0", [optional: true, hex: :postgrex]}
remote:
remote:   Ensure they match or specify one of the above in your deps and set "override: true"
remote: ** (Mix) Can't continue due to errors on dependencies
```

After some digging around, the problem lies with https://github.com/elixir-lang/elixir/issues/4191 which the solution is to nuke the `_build` folder upon new deployment.

As the current buildpack does not support just skipping the reuse of `_build` folder, I had to rebuild the entire app, to ensure the `_build` folder isn't reused. With this, the problem went away.

It would be great if we have support for this, perhaps via ENV variable, since it doesn't seem to be a permanent option to be committed.

**Comment by HashNuke** [comment]
@seantanly You can use the `always_rebuild` option in the buildpack config once. Then make another push by removing this option.
Documentation is in the readme.

**Comment by ericmj** [comment]
You can use this addon https://github.com/heroku/heroku-repo to manually purge the cache. Since this is a temporary issue in Elixir I am not concerned about the additional build time for rebuilding the app, it should be a one time thing.

**Comment by seantanly** [comment]
Thanks for the really fast replies! :D

@HashNuke Thanks, I did precisely that, adding 2 commits to resolve this issue. Just thinking ahead there could be similar future issues that crops up which necessitate a invalidation of build cache. This will come in really handy then.

@ericmj Thanks for the add-on recommendation! Doesn't look good if we need to add all those commits to many apps repositories... ;)

**Comment by seantanly** [comment]
@ericmj just tried the heroku-repo plugin on Dokku 0.4.13, doesn't seem to be compatible. Looks like `always_rebuild` is the only solution now, other than recreating the app.

**Comment by HashNuke** [comment]
@seantanly if these commits showing up in the git history is a problem then just create another branch locally and push that to Heroku/Dokku: "git push heroku foo:master"
You can then delete that local branch and force push git master to Heroku/Dokku when the build is fixed.

**Comment by seantanly** [comment]
@HashNuke That's a good suggestion! I can use that for apps that I can push directly to servers. For shared repo going through deployment flow such as GitHub > CI > Heroku/Dokku, will just have to fallback on the `always_rebuild` commits.
