### ISSUE TITLE
set MIX_ENV

### ISSUE THREAD

**Issue by steffenix** [HashNuke/heroku-buildpack-elixir#67]
I have tried to set the MIX_ENV to a custom value but it still using prod on heroku.

**Comment by ericmj** [comment]
I can't reproduce this, at work we have an environment where MIX_ENV is set to `staging` and it works. How do you set MIX_ENV and how do you verify that it's set?

**Comment by steffenix** [comment]
Using the console and checked using iex -S mix

**Comment by ericmj** [comment]
Please provide a project and the full steps to reproduce because I am unable to.

**Comment by steffenix** [comment]
@ericmj using phoenix_chat_example I get prod environment:

`git clone git@github.com:chrismccord/phoenix_chat_example.git
cd phoenix_chat_example
heroku create --buildpack "https://github.com/HashNuke/heroku-buildpack-elixir.git"
git push heroku master
heroku config:set MIX_ENV=staging
System.get_env("MIX_ENV")
"prod"
`

**Comment by ericmj** [comment]
You need to rebuild the project after setting MIX_ENV because apparently .profile.d overrides your heroku config.

**Comment by steffenix** [comment]
ok with
git commit --allow-empty -m "rebuild"
git push heroku master
