### ISSUE TITLE
rebar: Command not found

### ISSUE THREAD

**Issue by aesedepece** [HashNuke/heroku-buildpack-elixir#70]
Today I was deploying an Elixir app to a Dokku instance using this buildpack and failed to compile "ssl_verify_hostname".
```
===> ssl_verify_hostname
    rebar get-deps-compile
    make: rebar: Command not found
    make: *** [erl] Error 127
```
Full log is [here](https://gist.github.com/aesedepece/442185154cbe48458a1e#file-gistfile1-txt). 

It compiles just fine locally, and so it used to do remotely until a few days ago.

I have tried forcing full recompilation by putting `always_build_deps=true` inside `elixir_buildpack.config` without any luck.

Any clue? Thanks in advance!

**Comment by ericmj** [comment]
Can you show your `mix.exs` file?

Looks like ssl_verify_hostname builds with make which indicates you declared it in the top-level project. You can either remove it from your dependencies or declare it as `{:ssl_verify_hostname, ..., manager: :rebar}`.

**Comment by ericmj** [comment]
Also sent to PR to the project https://github.com/deadtrickster/ssl_verify_fun.erl/pull/12

**Comment by aesedepece** [comment]
I hadn't `:ssl_verify_hostname` in my mix.exs file, but then added it pointing to a fork of the original package, tried to deploy, removed it back and then deploy started working with exactly same code as yesterday.

Maybe something went weird in my environment... Anyway thanks a lot for the PR as it will help make sure this won't likely happen again in the future.
