### ISSUE TITLE
Configure build path

### ISSUE THREAD

**Issue by zberkom** [HashNuke/heroku-buildpack-elixir#72]
I'm trying to use this build-pack to deploy to heroku in a more uniq way and I'm running into some difficulty. Basically, we're storing our mobile react-native and phoenix code within the same repo at /mobile and /web respectively.

I forked this project and edited the compile script to include `/web` in the `build_path`, which made it compile, but now when heroku runs my procfile: `web: cd web/ && mix phoenix.server `, I get `app[web.1]: bash: mix: command not found` in my server logs. 

Should I edit the `cache_path` and `env_path` variables in `bin/compile` to include the `/web` path to ensure that `mix` is available? Also, elixir is not available if I run bash on heroku in both the root and web directories.

Looking forward to everyones thoughts' and suggestions.

**Comment by ericmj** [comment]
Why don't you create two separate apps for them?

**Comment by zberkom** [comment]
@ericmj Because the mobile team will be working on the mobile side of things as well as the API, so it made sense to make it easier for them to have just 1 PR to implement a feature. It also builds better awareness of what the team as a whole is working on and makes it easier to collaborate.

**Comment by ericmj** [comment]
Heroku buildpacks wasn't built for that so I would suggest either separating the apps or use another service than Heroku. You may be able to hack around it but there are no guarantees.

**Comment by zberkom** [comment]
@ericmj Turns out all I needed was (git subtree)[https://github.com/apenwarr/git-subtree/blob/master/git-subtree.txt]. Now I just deploy the web directory as if it was it's own repository, while maintaining both web and mobile within the same repo.
