### ISSUE TITLE
Export PATH to erl/elixir/hex for multi-buildpack scenario

### ISSUE THREAD

**Issue by Burgestrand** [HashNuke/heroku-buildpack-elixir#73]
This would allow heroku-buildpack-elixir to be used in a multi-buildpack scenario: https://devcenter.heroku.com/articles/buildpack-api#composing-multiple-buildpacks

It's probably a good idea to also export `MIX_ENV`.

**Comment by ericmj** [comment]
A pull request would be appreciated.

**Comment by Burgestrand** [comment]
Hah, wow, every amend creates its own reference to this issue. Sorry about that!

**Comment by Burgestrand** [comment]
I've opened a PR, so I'm closing this.
