### ISSUE TITLE
Erlang 19.0 is out there!

### ISSUE THREAD

**Issue by KamilLelonek** [HashNuke/heroku-buildpack-elixir#78]
There's a new `19.0` erlang version:

https://github.com/erlang/otp/tree/OTP-19.0

It can be updated as: https://s3.amazonaws.com/heroku-buildpack-elixir/erlang/cedar-14/OTP-19.0.tar.gz

**Comment by ericmj** [comment]
@KamilLelonek We have started the build for it https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/pull/11. It should be available in a few minutes.
