### ISSUE TITLE
Could not find "rebar3" when starting process

### ISSUE THREAD

**Issue by svileng** [HashNuke/heroku-buildpack-elixir#84]
I've been using the same buildpack config file for my Phoenix app, and suddenly the app failed to start on my staging server. The deploy is successful, but then errors when Heroku tries to start the server:

```
2016-08-24T17:39:22.238589+00:00 heroku[web.1]: Starting process with command `MIX_ENV=prod mix phoenix.server`
2016-08-24T17:39:26.118100+00:00 app[web.1]: Shall I install rebar3? (if running non-interactively, use: "mix local.rebar --force") [Yn] ** (Mix) Could not find "rebar3" to compile dependency :idna, please ensure "rebar3" is available
2016-08-24T17:39:26.115713+00:00 app[web.1]: Could not find "rebar3", which is needed to build dependency :idna
2016-08-24T17:39:26.115728+00:00 app[web.1]: I can install a local copy which is just used by Mix
2016-08-24T17:39:26.206034+00:00 heroku[web.1]: Process exited with status 1
2016-08-24T17:39:26.222993+00:00 heroku[web.1]: State changed from starting to crashed
```

**mix.exs**

```elixir
defmodule MyApp.Mixfile do
  use Mix.Project

  def project do
    [app: :myapp,
     version: "0.0.1",
     elixir: "~> 1.2",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     aliases: aliases(),
     deps: deps(),
     test_coverage: [tool: ExCoveralls],
     preferred_cli_env: ["coveralls": :test, "coveralls.detail": :test, "coveralls.post": :test, "coveralls.html": :test]]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [mod: {MyApp, []},
     applications: [:phoenix, :phoenix_pubsub, :phoenix_html, :cowboy, :logger, :gettext,
                    :phoenix_ecto, :postgrex, :comeonin, :timex, :bamboo]]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [{:phoenix, "1.2.1"},
     {:phoenix_pubsub, "1.0.0"},
     {:phoenix_ecto, "3.0.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "2.6.0"},
     {:gettext, "0.11.0"},
     {:cowboy, "1.0.4"},
     {:comeonin, "2.5.2"},
     {:guardian, "0.12.0"},
     {:guardian_db, "0.7.0"},
     {:timex, "3.0.5"},
     {:bamboo, "0.7.0"},
     {:number, "0.4.2"},
     {:phoenix_live_reload, "1.0.5", only: :dev},
     {:mix_test_watch, "0.2.6", only: :dev},
     {:excoveralls, "0.5.5", only: :test}]
  end

  # Aliases are shortcuts or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    ["ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
     "ecto.reset": ["ecto.drop", "ecto.setup"],
     "test": ["ecto.create --quiet", "ecto.migrate", "test"]]
  end
end
```

**elixir_buildpack.config**

```
# Elixir version
elixir_version=1.3.0

# Always rebuild from scratch on every deploy?
always_rebuild=true

# ENV variables
config_vars_to_export=(DATABASE_URL HOST SENDGRID_KEY)
```

I can't see any changes in the buid log before and after the app started crashing; it says that rebar3 is installed:

```
-----> Installing rebar
* creating /app/.mix/rebar
* creating /app/.mix/rebar3
```

Any help will be greatly appreciated! Thanks!

**Comment by svileng** [comment]
Looks like the problem was that I was setting `MIX_ENV` to `staging` (for which I have a `staging.exs` config file with a different host name) on that Heroku account; changing that to `prod` solved the problem and the dyno kicked the server running again.

Is there a workaround to making this work on Heroku with a `MIX_ENV` other than `prod`?

**Comment by ericmj** [comment]
It sounds weird that setting MIX_ENV would be related to rebar being missing, I think there's another issue here. I run applications with MIX_ENV=staging without issues.

**Comment by svileng** [comment]
Agree — the app was working before on staging, so I'm not sure what exactly have changed. I filed a ticket on Heroku and unfortunately they said this was out of their scope of support; but the support person did point out the difference in the `_build` folder (`staging` vs `prod` between my staging and production applications), which led me to changing the `MIX_ENV` value on staging.

Before doing that, I tried creating a new Heroku account from scratch with identical ENV variables to the staging one (including `MIX_ENV=staging`) — deploying the app on the new account resulted in the same error.

**Comment by svileng** [comment]
Right, found what the actual problem is — the `Procfile` was recently changed from `web: mix phoenix.server` to `web: MIX_ENV=prod mix phoenix.server`. The server should be using the same `MIX_ENV` as the on used to compile the dependencies. Closing the issue 👍

**Comment by luki3k5** [comment]
Hello, @svileng I have similar issue now. 
I am not sure I understand how you fixed it - Server compiles the code on the fly with the right ENV set on Heroku, could you please elaborate on what do you mean it should be using the same MIX_ENV?

**Comment by jorbs** [comment]
@svileng did you use the "Promote" feature in Heroku to release your app to production? I am facing the same issue after I've created the staging env. So basically, my app has a staging app with `MIX_ENV=staging` and when I promote it to prod, I get that `rebar3` error message.

**Comment by svileng** [comment]
@jorbs Sorry but I cannot remember, I can see this is from 2016, and my memory is not that good 😄
