### ISSUE TITLE
Example with Umbrella app

### ISSUE THREAD

**Issue by simonh1000** [HashNuke/heroku-buildpack-elixir#86]
I have written an umbrella app including a phoenix server. I can run it my using `mix phoenix.server` from `apps/server` but can't work out how to replicate that via the buildpack, procfile... on heroku itself

**Comment by wojtekmach** [comment]
@simonh1000 I've used the following with success:

```
# ./Procfile
web: cd apps/server && MIX_ENV=prod mix run --no-halt
```

btw, if you'll later have multiple web apps in your umbrella, one way to make it work on heroku is to use a proxy app in front that just forwards requests to other apps, e.g.: https://github.com/wojtekmach/acme_bank/blob/master/Procfile

**Comment by HashNuke** [comment]
@wojtekmach Thank you for responding to the issue.

@wojtekmach @simonh1000 IF the solution is still valid. Please feel free to contribute a note to the readme.

Closing issue.
