### ISSUE TITLE
Plug app having trouble binding to Heroku's port

### ISSUE THREAD

**Issue by enilsen16** [HashNuke/heroku-buildpack-elixir#89]
similar to https://github.com/gjaldon/heroku-buildpack-phoenix-static/issues/23

I can't seem to get my Plug app to bind to Heroku's Port. 

My `config_vars_to_export`-
```
config_vars_to_export=(DATABASE_URL POOL_SIZE PORT MIX_ENV)
```
My supervisor -
```
defmodule Hook do
  use Application

  @port Application.get_env(:hook, :port)

  # See http://elixir-lang.org/docs/stable/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    # Define workers and child supervisors to be supervised
    children = [
      supervisor(Hook.Repo, []),
      # Starts a worker by calling: Hook.Worker.start_link(arg1, arg2, arg3)
      Plug.Adapters.Cowboy.child_spec(:http, Hook.Router, %{}, [port: @port])
    ]
    
    # See http://elixir-lang.org/docs/stable/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Hook.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```
in `config/config.ex` -
```
config :hook, port: String.to_integer(System.get_env("PORT") || "4001")
```

Any ideas?

**Comment by ericmj** [comment]
Module attributes are assigned when the module is compiled and heroku does not provide the port at that time. If you move the Application.get_env to the function body it should work.

**Comment by enilsen16** [comment]
Yeah that was it. Is it a good rule of thumb to never use module attributes with `Application.get_env` or `System.get_env`?

**Comment by ericmj** [comment]
> Is it a good rule of thumb to never use module attributes with Application.get_env or System.get_env?

Not generally. But you have to consider values set at runtime vs compile time.
